spring.datasource.url=jdbc:postgresql://localhost:5432/carshowroom
spring.datasource.username=postgres
spring.datasource.password=Talha111008

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true